[versions]
accompanist = "0.32.0"
amplitude = "1.12.2"
androidGradlePlugin = "8.1.2"
androidMaterial = "1.10.0"
androidxActivityCompose = "1.8.0"
androidxComposeBom = "2023.10.01"
androidxComposeCompiler = "1.5.6"
androidxCore = "1.12.0"
androidxCoreSplashScreen = "1.0.1"
androidxEspresso = "3.5.1"
androidxHiltCompose = "1.1.0-rc01"
androidxLifecycle = "2.6.2"
androidxJunit = "1.1.5"
androidxStartup = "1.1.1"
androidxTestRunner = "1.5.2"
androidxDatastore = "1.0.0"
androidDesugar = "2.0.3"
chucker = "4.0.0"
coil = "2.5.0"
composeDestinations = "1.9.55"
detektGradlePlugin = "1.23.4"
firebaseAppDistributionGradlePlugin = "4.0.1"
firebaseCrashlyticsGradlePlugin = "2.9.9"
firebaseBom = "32.4.0"
fladleGradlePlugin = "0.17.4"
googleServicesGradlePlugin = "4.4.0"
kotest = "5.8.0"
kotlin = "1.9.21"
kotlinCoroutines = "1.7.3"
kotlinSerializationJson = "1.6.2"
kotlinSnapshot = "2.3.0"
koverGradlePlugin = "0.6.1"
ksp = "1.9.21-1.0.16"
ktlint = "0.45.2"
ktlintGradlePlugin = "11.6.1"
hilt = "2.50"
javapoet = "1.13.0"
junit = "5.10.1"
junitKotlinExtensions = "0.0.3"

jwt = "2.0.2"
mockk = "1.13.8"
mockWebServer = "4.12.0"
mockWebServer-pathDispatcher = "1.1.7"
paging = "3.2.1"
paparazzi = "1.3.1"
retrofit = "2.9.0"
retrofitGsonConverter = "2.9.0"
robolectric = "4.11.1"
room = "2.6.1"
turbine = "1.0.0"
twitter-compose-rules-detekt = "0.0.26"
testparameterinjector = "1.12"
datadog = "2.4.0"
datadogGradlePlugin = "1.12.0"

[libraries]
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
datadog-gradlePlugin = { group = "com.datadoghq", name = "dd-sdk-android-gradle-plugin", version.ref = "datadogGradlePlugin" }
detekt-gradlePlugin = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detektGradlePlugin" }
firebase-appDistribution-gradlePlugin = { group = "com.google.firebase", name = "firebase-appdistribution-gradle", version.ref = "firebaseAppDistributionGradlePlugin" }
firebase-crashlytics-gradlePlugin = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsGradlePlugin" }
fladle-gradlePlugin = { group = "com.osacky.flank.gradle", name = "fladle", version.ref = "fladleGradlePlugin" }
google-services-gradlePlugin = { group = "com.google.gms", name = "google-services", version.ref = "googleServicesGradlePlugin" }
hilt-gradlePlugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt" }
karumi-kotlinsnapshotPlugin = { module = "com.karumi.kotlinsnapshot:plugin", version.ref = "kotlinSnapshot" }
karumi-kotlinsnapshotCore = { module = "com.karumi.kotlinsnapshot:core", version.ref = "kotlinSnapshot" }
ktlint-gradlePlugin = { group = "org.jlleitschuh.gradle", name = "ktlint-gradle", version.ref = "ktlintGradlePlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kover-gradlePlugin = { group = "org.jetbrains.kotlinx", name = "kover", version.ref = "koverGradlePlugin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
paparazzi-gradlePlugin = { group = "app.cash.paparazzi", name = "paparazzi-gradle-plugin", version.ref = "paparazzi" }

amplitude-analytics = { group = "com.amplitude", name = "analytics-android", version.ref = "amplitude" }

android-tools-desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugar" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivityCompose" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "androidxCore" }
androidx-core-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxCoreSplashScreen" }
androidx-hilt-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltCompose" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidxDatastore" }
androidx-datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "androidxDatastore" }
androidx-startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "androidxStartup" }

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-material = { group = "androidx.compose.material", name = "material" }
androidx-compose-material-icons = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-compiler = { group = "androidx.compose.compiler", name = "compiler", version.ref = "androidxComposeCompiler" }

chucker-debug = { group = "com.github.chuckerteam.chucker", name = "library", version.ref = "chucker" }
chucker-noop = { group = "com.github.chuckerteam.chucker", name = "library-no-op", version.ref = "chucker" }

compose-destinations-animations-core = { group = "io.github.raamcosta.compose-destinations", name = "animations-core", version.ref = "composeDestinations" }
compose-destinations-ksp = { group = "io.github.raamcosta.compose-destinations", name = "ksp", version.ref = "composeDestinations" }
compose-rules = { group = "com.twitter.compose.rules", name = "detekt", version.ref = "twitter-compose-rules-detekt" }

coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

datadog-rum = { group = "com.datadoghq", name = "dd-sdk-android-rum", version.ref = "datadog" }
datadog-okhttp = { group = "com.datadoghq", name = "dd-sdk-android-okhttp", version.ref = "datadog" }
datadog-trace = { group = "com.datadoghq", name = "dd-sdk-android-trace", version.ref = "datadog" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-remote-config = { module = "com.google.firebase:firebase-config" }
firebase-cloud-messaging = { module = "com.google.firebase:firebase-messaging" }

google-accompanist-pager = { group = "com.google.accompanist", name = "accompanist-pager", version.ref = "accompanist" }
google-accompanist-webview = { group = "com.google.accompanist", name = "accompanist-webview", version.ref = "accompanist" }
google-accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }

hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-library = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-core = { group = "com.google.dagger", name = "hilt-core", version.ref = "hilt" }
hilt-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }

javapoet = { group = "com.squareup", name = "javapoet", version.ref = "javapoet" }

material = { group = "com.google.android.material", name = "material", version.ref = "androidMaterial" }

kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinSerializationJson" }

junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
junit-params = { group = "org.junit.jupiter", name = "junit-jupiter-params" }
junit-kotlinextensions = { group = "de.jodamob.junit5", name = "junit5-kotlin", version.ref = "junitKotlinExtensions" }
junit-vintage = { group = "org.junit.vintage", name = "junit-vintage-engine", version.ref = "junit" }

jwt = { module = "com.auth0.android:jwtdecode", version.ref = "jwt" }

kotest-bom = { group = "io.kotest", name = "kotest-bom", version.ref = "kotest" }
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core" }
kotest-runner-junit5 = { group = "io.kotest", name = "kotest-runner-junit5" }

mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }

mockwebserver-pathdispatcher = { module = "pl.droidsonroids.testing:mockwebserver-path-dispatcher", version.ref = "mockWebServer-pathDispatcher" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockWebServer" }

paging = { module = "androidx.paging:paging-common", version.ref = "paging" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }
paging-testing = { module = "androidx.paging:paging-testing", version.ref = "paging" }

paparazzi = { group = "app.cash.paparazzi", name = "paparazzi", version.ref = "paparazzi" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofitGsonConverter" }

robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-common = { module = "androidx.room:room-common", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

testparameterinjector = { group = "com.google.testparameterinjector", name = "test-parameter-injector", version.ref = "testparameterinjector" }

turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
